apiVersion: mesh.lite.io/v1alpha1
kind: Service
metadata:
  name: mesh-server
spec:
  container:
    name: mesh-server
    image: mirage20/k8s-debug-tools
    command: ["/bin/bash"]
    args: ["-c", "while true ; do { nc -l -p 2000 -c 'echo \"$(date)\"';} done"]
    ports:
    - containerPort: 2000
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
